---
title: "prep data"
author: "Clayton T. Lamb"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: github_document
---

```{r render, eval=FALSE,include=FALSE}
# rmarkdown::render(here::here("jags", 'run_IPM.Rmd'),
#                   output_file =  "README.md")
#
 knitr::purl(input=here::here("scripts_r", '1.prep_data.Rmd'),
                   output =  here::here("scripts_r", '1.prep_data.r'))
```

## Load Data

```{r Load packages and data, results='hide', message=FALSE, warning=FALSE}
library(tidybayes)
library(ggmcmc)
library(hrbrthemes)
library(tidylog)
library(tidyverse)

# Load data ---------------------------------------------------------------

hd <- read.csv(here::here("data/clean/blueprint.csv"))
hn <- hd %>%
  dplyr::select(herd, herd_num)
sgt <- read.csv(here::here("data/clean/herd_sightability.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
afs <- read.csv(here::here("data/clean/survival.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
afr <- read.csv(here::here("data/clean/recruitment.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
recruit.yr <-read.csv(here::here("data/clean/recruitment_counts.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
counts <- read.csv(here::here("data/clean/counts.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
trt <- read.csv(here::here("data/clean/treatments.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")

sexratios <- read.csv(here::here("data/clean/sexratios.csv")) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd")
sexratio_summary <- read.csv(here::here("data/clean/sexratio_summary.csv"))
surv.yr <- read_csv(here::here("data/clean/survival_yrly.csv"))%>%
  arrange(herd) %>%
  left_join(hn, by = "herd")

covariates <- read.csv(here::here("data/spatial/covariates_addPCA.csv")) %>%
  mutate(herd = case_when(
    herd == "Bearhole Redwillow" ~ "Narraway BC",
    TRUE ~ herd
  )) %>%
  arrange(herd) %>%
  left_join(hn, by = "herd") %>%
  drop_na()

# ##remove Jasper?
##get covar, S, and R, timing all figured out
```

## Restrict data to only years of demographic data not affected by recovery actions, and
## Restrict data to only years of covariate data

```{r filter recovery actions, results='hide', message=FALSE, warning=FALSE}
#### TREATMENT COMBOS
treatment.combos <- trt %>%
  filter(applied == 1) %>%
  group_by(herd, year) %>%
  summarize(
    trt = paste(
      gsub(" ", "", treatment), # Remove spaces
      collapse = "-" # Add - between treatments
    ),
    .groups = "drop"
  ) %>%
  dplyr::select(herd, year, trt)

yrs_keep <- 1985:2020 ## satellite data starts in 1894 and demographic effects realized following March.

remove.trts <- treatment.combos %>%
  #filter(trt != "transplant") %>% ## this was coded as years following the transplant and it had no effect, so retain
  distinct(trt) %>%
  pull(trt)

afs <- afs %>%
  left_join(treatment.combos %>% mutate(year - 1), by = c("herd", "year")) %>% ## S data coded as start of year so survival to March 2022 is 2021 (so year-1)
  filter(!trt %in% remove.trts) %>%
  ## remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991) - 1),
    !(herd %in% "Telkwa" & year %in% c(1997:1999) - 1),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989) - 1),
    !(herd %in% "Purcell South" & year %in% c(2012:2013) - 1)
  ) %>%
  filter(year %in% yrs_keep)

afr <- afr %>%
  left_join(treatment.combos, by = c("herd", "year")) %>%
  filter(!trt %in% remove.trts) %>%
  ## remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991)),
    !(herd %in% "Telkwa" & year %in% c(1997:1999)),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989)),
    !(herd %in% "Purcell South" & year %in% c(2012:2013))
  ) %>%
  filter(year %in% yrs_keep)

counts <- counts %>%
  left_join(treatment.combos, by = c("herd", "year")) %>%
  filter(!trt %in% remove.trts) %>%
  ## remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991)),
    !(herd %in% "Telkwa" & year %in% c(1997:1999)),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989)),
    !(herd %in% "Purcell South" & year %in% c(2012:2013))
  ) %>%
  filter(year %in% yrs_keep)

sexratios <- sexratios %>%
  left_join(treatment.combos, by = c("herd", "year")) %>%
  filter(!trt %in% remove.trts) %>%
  ## remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991)),
    !(herd %in% "Telkwa" & year %in% c(1997:1999)),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989)),
    !(herd %in% "Purcell South" & year %in% c(2012:2013))
  ) %>%
  filter(year %in% yrs_keep)

surv.yr <- surv.yr%>%
  left_join(treatment.combos, by=c("herd","year"))%>%
  filter(!trt%in%remove.trts)%>%
  ##remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991)),
    !(herd %in% "Telkwa" & year %in% c(1997:1999)),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989)),
    !(herd %in% "Purcell South" & year %in% c(2012:2013))
  ) %>%
  filter(year %in% yrs_keep)

recruit.yr <- recruit.yr%>%
  left_join(treatment.combos, by=c("herd","year"))%>%
  filter(!trt%in%remove.trts)%>%
  ##remove years during transplant, where pop growing due to directly adding animals
  filter(
    !(herd %in% "Charlotte Alplands" & year %in% c(1984:1991)),
    !(herd %in% "Telkwa" & year %in% c(1997:1999)),
    !(herd %in% "South Selkirks" & year %in% c(1987:1989)),
    !(herd %in% "Purcell South" & year %in% c(2012:2013))
  )%>%
  filter(year%in%yrs_keep)

covariates <- covariates %>%
  filter(year %in% (min(yrs_keep)-1):max(yrs_keep)) ##covariates at y-1 should impact demography at year y (maybe or perhaps need even greater lag)x
```

## Prep data for IPM

```{r Prep data for IPM, results='hide', message=FALSE, warning=FALSE}
# Herds and herd number
herds <- unique(hd$herd)
nherd <- nrow(hn)
nsight_grp <- length(unique(hd$sight_grp))

#  Years of study
yrs <- seq(from = min(counts$year), to = max(counts$year), by = 1)
nyr <- length(yrs)
yr_idx <- seq(from = 1, to = nyr, by = 1)
yr_df <- as.data.frame(cbind(yrs, yr_idx))

# Age classes
nage <- 2

# Restrict year range for trouble shooting
rest_yr <- nyr
ntrt <- length(unique(trt$treatment))




## Covariates
## scale all covariates
covariates <- covariates %>%
  mutate(across(dist.all:clim2,
         .fns=~scale(.x, center=TRUE)%>%as.numeric(),
         .names="{col}_scale")) %>%
  mutate(year = year + 1) %>%
  left_join(yr_df, by = c("year" = "yrs"))

dist.all <- covariates %>%
  select(herd_num, yr_idx, dist.all_scale) %>%
  arrange(herd_num, yr_idx) %>%
  pivot_wider(names_from = yr_idx, values_from = dist.all_scale, values_fill = NA) %>%
  select(-herd_num)

clim1 <- covariates %>%
  select(herd_num, yr_idx, clim1_scale) %>%
  arrange(herd_num, yr_idx) %>%
  pivot_wider(names_from = yr_idx, values_from = clim1_scale, values_fill = NA) %>%
  select(-herd_num)

clim2 <- covariates %>%
  select(herd_num, yr_idx, clim2_scale) %>%
  arrange(herd_num, yr_idx) %>%
  pivot_wider(names_from = yr_idx, values_from = clim2_scale, values_fill = NA) %>%
  select(-herd_num)

## Recruitment
 recruit.yr.priors <- recruit.yr%>%
   ##with duplicates removed so data in priors and IPM are same.
  ## choose which recruitment survey type to use, hierarchy is OSC>MNKA>OTC
  ## choose which survey month to use if >1, 9>5>1
  group_by(herd,year)%>%
  mutate(type=factor(type,levels=c("OSC","MNKA","OTC")),
        season.num=case_when(season=="spring"~1,
                              season=="fall"~5,
                              season=="winter"~9))%>%
  arrange(herd,year,-season.num, type)%>%
  slice(1)%>%
   ##add in count type matrix
      mutate(
         type.otc=case_when(type=="OTC"~1, TRUE~0),
                  type.osc=case_when(type=="OSC"~1, TRUE~0),
                  type.mnka=case_when(type=="MNKA"~1, TRUE~0),
         adults=case_when(adults==0~1, TRUE~adults))%>%
     left_join(yr_df, by = c("year" = "yrs"))%>%
   left_join(covariates%>%select(herd,year,dist.all_scale,clim1_scale,clim2_scale), by=c("herd", "year"))%>%
   ungroup%>%
  select(herd=herd_num,year=yr_idx,events=calves,trials=adults,dist.all_scale,clim1_scale,clim2_scale,season.num,type.otc:type.mnka)
 
 
recruit.yr.ipm <-  recruit.yr.priors%>%
  select(herd,year,events,trials,season.num,type.otc:type.mnka)


nr <- nrow(recruit.yr.ipm)


# Survival

surv.yr.priors <-surv.yr%>%
  left_join(yr_df, by = c("year" = "yrs"))%>%
     left_join(covariates%>%select(herd,year,dist.all_scale,clim1_scale,clim2_scale), by=c("herd", "year"))%>%
  select(herd=herd_num,year=yr_idx,event,time,dist.all_scale,clim1_scale,clim2_scale)

surv.yr.ipm <- surv.yr.priors%>%
    group_by(herd,year)%>%
  summarise(events=sum(event),
            trials=sum(time))%>%
  ungroup%>%
  select(herd,year,events,trials)

ns <- nrow(surv.yr.ipm)


# Sightability
# Estimates of 1 are not usable here, not sure why they are left in or how this
# even works given qlogis(1) equals Inf
# We need to transform the uncertainty along with the mean, changes made in JAGS
grp_p <- sgt %>%
  left_join(hd, by = c("herd", "herd_num")) %>%
  group_by(sight_grp) %>%
  mutate(
    n = n(),
    mean_grp_p = mean(est, na.rm = TRUE),
    mean_grp_pvar = mean(sd^2, na.rm = TRUE), 
    mean_grp_ptau = 1 / (mean_grp_pvar)
  ) %>%
  slice(1) %>%
  as.data.frame() %>%
  dplyr::select(sight_grp, mean_grp_p, mean_grp_pvar, mean_grp_ptau) %>%
  arrange(sight_grp)


mean_grp_p <- grp_p$mean_grp_p
mean_grp_ptau <- grp_p$mean_grp_ptau

sgt_grp_ind <- matrix(nrow = nherd, ncol = nyr)
for (sg in 1:nrow(sgt_grp_ind)) {
  sgt_grp_ind[sg, ] <- hd$sight_grp[hd$herd_num == sg]
}



# Abundance -- separate out rows where no sightability data provided

# Survey counts (have sightability)
cdat <- counts %>%
  dplyr::filter(!is.na(Sightability)) %>%
  mutate(
    herd = herd_num,
    age = NA,
    sex = NA,
    mu = as.integer(count),
    tau = case_when(
      count > 0 ~ 1 / ((count * 0.15)^2),
      count %in% 0 ~ 1
    )
  ) %>%
  # tau = 1/(sd*sd)) %>%
  left_join(yr_df, by = c("year" = "yrs")) %>%
  dplyr::select(herd, year = yr_idx, age, sex, mu, tau) %>%
  dplyr::filter(year <= rest_yr) %>%
  arrange(herd, year)

nc <- nrow(cdat)


# Sightability data
pdat <- counts %>%
  left_join(hd, by = c("herd", "herd_num")) %>%
  dplyr::filter(!is.na(Sightability)) %>%
  mutate(
    herd = herd_num,
    age = NA,
    sex = NA,
    mu = Sightability,
    tau = 1 / (sd * sd)
  ) %>%
  left_join(yr_df, by = c("year" = "yrs")) %>%
  dplyr::select(herd, year = yr_idx, age, sex, mu, tau) %>%
  dplyr::filter(year <= rest_yr) %>%
  arrange(herd, year)
# pdat$pdat[pdat$pdat == 1] <- 0.95
pdat$tau[pdat$tau == "Inf"] <- mean(pdat$tau[pdat$tau != "Inf"])
np <- nrow(pdat)

# Minimum Estimates
edat <- counts %>%
  dplyr::filter(is.na(Sightability)) %>%
  left_join(hd, by = c("herd", "herd_num")) %>%
  mutate(
    herd = herd_num,
    age = NA,
    sex = NA,
    mu = as.integer(count),
    tau = case_when(
      count > 0 ~ 1 / ((count * 0.2)^2),
      count %in% 0 ~ 10
    ),
    # tau = 1/(sd*sd),
    sight_grp = sight_grp
  ) %>%
  left_join(yr_df, by = c("year" = "yrs")) %>%
  dplyr::select(herd, year = yr_idx, age, sex, mu, tau, sight_grp) %>%
  dplyr::filter(year <= rest_yr) %>%
  arrange(herd, year)


ne <- nrow(edat)


# Survey timing: most are in March. Those NOT in March:
# 1 = March (reference), 2 = Fall, 3 = Spring

survey_timing <- recruit.yr.ipm %>%
  dplyr::select(herd, year, season.num) %>%
  rbind(expand.grid(
    herd = (1:nherd)[!(1:nherd) %in% unique(recruit.yr.ipm$herd)],
    # yr_idx=(1:nyr)[!(1:nyr)%in%unique(afr%>%
    #                                     left_join(yr_df, by = c("year" = "yrs"))%>%pull(yr_idx))],
    year = 1,
    season.num = 1
  )) %>%
  tidyr::spread(year, season.num)
survey_timing <- survey_timing[, -1]
survey_timing[is.na(survey_timing)] <- 1


# Calves born in May
# May/Jun survey = Spring survey (age = 1 month) --- season_int = 3
# Oct survey = Fall survey (age = 5 months) ---- season_int = 2
# Mar survey = winter survey (age = 10 months) ---- season_int = 1

month_offset <- survey_timing
month_offset[month_offset == 1] <- 0
month_offset[month_offset == 2] <- 5 # 5 units offset
month_offset[month_offset == 3] <- 9 # 9 units offset


##count type matrices
count.otc <- recruit.yr.ipm %>%
  dplyr::select(herd, year, type=type.otc) %>%
  rbind(expand.grid(
    herd = (1:nherd)[!(1:nherd) %in% unique(recruit.yr.ipm$herd)],
    # yr_idx=(1:nyr)[!(1:nyr)%in%unique(afr%>%
    #                                     left_join(yr_df, by = c("year" = "yrs"))%>%pull(yr_idx))],
    year = 1,
    type = 1
  )) %>%
  tidyr::spread(year, type)
count.otc <- count.otc[, -1]
count.otc[is.na(count.otc)] <- 0 ##does this matter? if its 0 or 1? presumably these are missing data?


count.osc <- recruit.yr.ipm %>%
  dplyr::select(herd, year, type=type.osc) %>%
  rbind(expand.grid(
    herd = (1:nherd)[!(1:nherd) %in% unique(recruit.yr.ipm$herd)],
    # yr_idx=(1:nyr)[!(1:nyr)%in%unique(afr%>%
    #                                     left_join(yr_df, by = c("year" = "yrs"))%>%pull(yr_idx))],
    year = 1,
    type = 1
  )) %>%
  tidyr::spread(year, type)
count.osc <- count.osc[, -1]
count.osc[is.na(count.osc)] <- 0 


count.mnka <- recruit.yr.ipm %>%
  dplyr::select(herd, year, type=type.mnka) %>%
  rbind(expand.grid(
    herd = (1:nherd)[!(1:nherd) %in% unique(recruit.yr.ipm$herd)],
    # yr_idx=(1:nyr)[!(1:nyr)%in%unique(afr%>%
    #                                     left_join(yr_df, by = c("year" = "yrs"))%>%pull(yr_idx))],
    year = 1,
    type = 1
  )) %>%
  tidyr::spread(year, type)
count.mnka <- count.mnka[, -1]
count.mnka[is.na(count.mnka)] <- 0 


# # Starting population size of each herd
# take average of all counts that occured within 3 years of first count per herd
#   Using the "Est_CL" column
# Starting population size of each herd
meancount <- counts %>%
  arrange(herd_num, year) %>%
  group_by(herd_num) %>%
  mutate(keep = year - min(year)) %>%
  dplyr::filter(keep < 4) %>%
  mutate(n1_mean = mean(Est_CL, na.rm = TRUE)) %>%
  slice(1) %>%
  as.data.frame() %>%
  dplyr::select(herd, herd_num, n1_mean) %>%
  right_join(hd, by = c("herd", "herd_num")) %>%
  mutate(n1_mean = ifelse(is.na(n1_mean), mean(n1_mean, na.rm = TRUE), n1_mean)) %>%
  arrange(herd_num)
n1s <- meancount$n1_mean

## starting age class distribution (sensitivity tested this in McNay et al. 2022 and it doesnt have a meaningful effect even if substantially changed)
n1 <- matrix(NA, nrow = nherd, ncol = nage)
for (h in 1:nherd) {
  n1[h, 1] <- (n1s[h] * 0.5) * 0.15
  n1[h, 2] <- (n1s[h] * 0.64) * 0.85
}


# Sex ratio
srdat <- sexratios %>%
  mutate(
    herd = herd_num,
    mu = sratio,
    tau = 1 / (sratio.sd * sratio.sd)
  ) %>%
  left_join(yr_df, by = c("year" = "yrs")) %>%
  dplyr::filter(!is.na(mu)) %>%
  dplyr::filter(mu != "Inf") %>%
  dplyr::select(herd, year = yr_idx, mu, tau) %>%
  dplyr::filter(year <= rest_yr) %>%
  arrange(herd, year) %>%
  distinct(herd, year, .keep_all = TRUE)

nsr <- nrow(srdat)

meansr <- array(NA, c(1, 2))
meansr[1, 1] <- sexratio_summary[1, 1]
meansr[1, 2] <- 1 / (sexratio_summary[1, 2]^2)


first <- rep(1, nherd)


#  First year of treatment for each herd
treatment_start <- trt %>%
  filter(applied == 1 & !treatment %in% c("transplant", "reduce moose")) %>%
  group_by(herd_num) %>%
  summarize(yr = min(year) - 1) %>% ## year before trt starts
  full_join(
    tibble(
      herd_num = 1:nherd,
      yr_fill = 2021
    ),
    by = "herd_num"
  ) %>%
  left_join(hd %>% dplyr::select(name = herd, herd_num)) %>%
  mutate(yrs = case_when(
    is.na(yr) ~ yr_fill,
    name %in% "Columbia North" ~ 2004, ## CN reduce moose did work so keep this one
    TRUE ~ yr
  )) %>%
  left_join(yr_df) %>%
  arrange(herd_num) %>%
  pull(yr_idx)


nyr <- rest_yr



## single digit params
single.params <- tibble(
  nherd = nherd,
  nage=2,
  nyr = nyr,
  nc = nc,
  ne = ne,
  ns = ns,
  nr = nr,
  nsr = nsr,
  nsight_grp=nsight_grp,
)
```

## Join S and R to covariates for data exploration

```{r Prep data for IPM, results='hide', message=FALSE, warning=FALSE}
sdat.plot <- read_csv(here::here("data/clean/survival.csv"))%>%
  left_join(covariates%>%
              mutate(year=year)%>% ##this should probably be year-1 but don't have enough covar data
              select(herd,year,dist.all,dist.all_scale,clim1,clim1_scale,clim2,clim2_scale),
            by=c("herd","year"))%>%
  pivot_longer(dist.all:clim2_scale)%>%
  mutate(value=as.numeric(value))

rdat.plot <- read_csv(here::here("data/clean/recruitment.csv"))%>%
  left_join(covariates%>%
              select(herd,year,dist.all,dist.all_scale,clim1,clim1_scale,clim2,clim2_scale),
            by=c("herd","year"))%>%
  pivot_longer(dist.all:clim2_scale)%>%
  mutate(value=as.numeric(value),
         season=case_when(season_int==1~10,
                          season_int==2~5,
                          season_int==3~1))

```

## Save data for IPM

```{r Save data for IPM, results='hide', message=FALSE, warning=FALSE}
## demographic data
write_csv(cdat, here::here("data/clean/forIPM/cdat.csv"))
write_csv(edat, here::here("data/clean/forIPM/edat.csv"))
write_csv(srdat, here::here("data/clean/forIPM/srdat.csv"))
write_csv(pdat, here::here("data/clean/forIPM/pdat.csv"))
write_csv(surv.yr.priors, here::here("data/clean/forIPM/surv.yr.priors.csv"))
write_csv(surv.yr.ipm, here::here("data/clean/forIPM/surv.yr.ipm.csv"))
write_csv(recruit.yr.priors, here::here("data/clean/forIPM/recruit.yr.priors.csv"))
write_csv(recruit.yr.ipm, here::here("data/clean/forIPM/recruit.yr.ipm.csv"))
write_csv(counts, here::here("data/clean/forIPM/counts.csv"))

## covariates
saveRDS(dist.all, here::here("data/clean/forIPM/dist.all.rds"))
saveRDS(clim1, here::here("data/clean/forIPM/clim1.rds"))
saveRDS(clim2, here::here("data/clean/forIPM/clim2.rds"))
write_csv(covariates, here::here("data/clean/forIPM/covariates_scaled.csv"))

## other
#write_csv(first_per_herd, here::here("data/clean/forIPM/first_per_herd.csv"))
write_csv(month_offset, here::here("data/clean/forIPM/month_offset.csv"))
write_csv(grp_p, here::here("data/clean/forIPM/grp_p.csv"))
write_csv(single.params, here::here("data/clean/forIPM/single.params.csv"))
write_csv(meancount, here::here("data/clean/forIPM/meancount.csv"))
write_csv(yr_df, here::here("data/clean/forIPM/yr_df.csv"))
write_csv(count.otc, here::here("data/clean/forIPM/count.otc.csv"))
write_csv(count.osc, here::here("data/clean/forIPM/count.osc.csv"))
write_csv(count.mnka, here::here("data/clean/forIPM/count.mnka.csv"))



##plot data
write_csv(rdat.plot, here::here("data/clean/forIPM/rdat.plot.csv"))
write_csv(sdat.plot, here::here("data/clean/forIPM/sdat.plot.csv"))
 

#FOR without Jasper
# ## demographic data
# write_csv(cdat, here::here("data/clean/forIPM/wo_Jasp/cdat.csv"))
# write_csv(edat, here::here("data/clean/forIPM/wo_Jasp/edat.csv"))
# write_csv(sdat, here::here("data/clean/forIPM/wo_Jasp/sdat.csv"))
# write_csv(rdat, here::here("data/clean/forIPM/wo_Jasp/rdat.csv"))
# write_csv(srdat, here::here("data/clean/forIPM/wo_Jasp/srdat.csv"))
# write_csv(pdat, here::here("data/clean/forIPM/wo_Jasp/pdat.csv"))
# 
# ## covariates
# saveRDS(dist.all, here::here("data/clean/forIPM/wo_Jasp/dist.all.rds"))
# saveRDS(clim1, here::here("data/clean/forIPM/wo_Jasp/clim1.rds"))
# 
# ## other
# write_csv(first_per_herd, here::here("data/clean/forIPM/wo_Jasp/first_per_herd.csv"))
# write_csv(month_offset, here::here("data/clean/forIPM/wo_Jasp/month_offset.csv"))
# write_csv(grp_p, here::here("data/clean/forIPM/wo_Jasp/grp_p.csv"))
# write_csv(single.params, here::here("data/clean/forIPM/wo_Jasp/single.params.csv"))
# write_csv(meancount, here::here("data/clean/forIPM/wo_Jasp/meancount.csv"))
# write_csv(yr_df, here::here("data/clean/forIPM/wo_Jasp/yr_df.csv"))
# 
# ##plot data
# write_csv(rdat.plot, here::here("data/clean/forIPM/wo_Jasp/rdat.plot.csv"))
# write_csv(sdat.plot, here::here("data/clean/forIPM/wo_Jasp/sdat.plot.csv"))

```
